# Wrangler configuration for Cloudflare Workers deployment
name = "pulseq-public"
compatibility_date = "2025-06-05"

# Use modern Workers Assets for static site
[assets]
directory = "./site/"
not_found_handling = "404-page"
